### ISSUE TITLE
[News] Extra Spooky Events

### ISSUE THREAD

**Issue by doej1367** [InventivetalentDev/HypixelMagmaBossTimer#11]
https://twitter.com/jayavarmen/status/1189362796208840705
Thought I'd tell you, maybe you want to add those...

**Comment by doej1367** [comment]
This means the next Spooky Event is in about an hour...

**Comment by InventivetalentDev** [comment]
Was thinking about adding those too, but I'm not gonna get around to doing that, unfortunately.
