### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by Alex-x90** [InventivetalentDev/HypixelMagmaBossTimer#6]
The site is currently down, when attempting to reach it, it looks like this:

![image](https://user-images.githubusercontent.com/40383341/63490033-919ae080-c468-11e9-99fa-21d37b14efe8.png)

**Comment by Th3Shadowbroker** [comment]
This problem already got reported on the discord. Looks like multiple services (also spiget) are affected. However Remote-Slide for example is running fine.

**Comment by Th3Shadowbroker** [comment]
@Alex-x90 Problem got solved.
