### ISSUE TITLE
Did the Calender Feature on the website break?

### ISSUE THREAD

**Issue by doej1367** [InventivetalentDev/HypixelMagmaBossTimer#81]
## What steps will reproduce the problem?  
1. go to https://hypixel.inventivetalent.org/
2. Click on 'Calender'
3. Be greeted with a spring '00th 00:00am Year 00'
![grafik](https://user-images.githubusercontent.com/19228364/99145566-4160fd00-2670-11eb-8ba9-6143d5a3b45a.png)

## What were you expecting to happen? What happened instead?  
I expected the correct ingame time to be displayed

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
none. this one is about the website

## Why the questionmark?
Well, I got a lot of ad- and script- blockers in my browser and I don't know if I got them all disabled on this website. but I think I did...

**Comment by InventivetalentDev** [comment]
should be working again :)
